#%RAML 1.0

# AMWA NMOS Event & Tally Specification: Events API
# (c) AMWA 2018

title: Events
baseUri: http://example.api.com/x-nmos/events/{version}
version: v1.0
mediaType: application/json
types:
  Base:
    type: !include schemas/base.json
  Sources:
    type: !include schemas/sources.json
  Source:
    type: !include schemas/source.json
  Event:
    type: !include schemas/event.json
  Type:
    type: !include schemas/type.json
  ErrorSchema:
    type: !include schemas/error.json
documentation:
  - title: Overview
    content: |
      The Events API is exposed by each NMOS Device in a system that supports AMWA NMOS Event & Tally Specification. The API is used to announce the type definitions used by the Event & Tally sources and for the receiving devices to be able to check the current source state.

/:
  displayName: Base
  get:
    description: List of paths available from this API
    responses:
      200:
        body:
          example: !include ../examples/eventsapi-v1.0-base-get-200.json
          type: Base
/sources:
  displayName: Sources
  get:
    description: List of the Event & Tally compatible sources
    responses:
      200:
        body:
          example: !include ../examples/eventsapi-v1.0-sources-get-200.json
          type: Sources
  /{sourceId}:
    uriParameters:
      sourceId:
        type: string
        pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
    get:
      description: Get a single source
      responses:
        200:
          body:
            example: !include ../examples/eventsapi-v1.0-sourceid-get-200.json
            type: Source
        404:
          description: Returned when the requested Source ID does not exist
          body:
            type: ErrorSchema
    /type:
      displayName: Type definition
      get:
        description: JSON containing detailed type information
        responses:
          200:
            body:
              example: !include ../examples/eventsapi-v1.0-type-boolean-get-200.json
              type: Type
    /state:
      displayName: Source state
      get:
        description: JSON containing the last state change notification sent over the transport protocols
        responses:
          200:
            body:
              example: !include ../examples/eventsapi-v1.0-state-boolean-get-200.json
              type: Event
